services:
  mysql:
    image: mysql:8.0
    container_name: teacher_student_system_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: teacher_student_system
      MYSQL_USER: user
      MYSQL_PASSWORD: teacher_student_system_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: